version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mimiki003
      MONGO_INITDB_ROOT_PASSWORD: mimiki003
    command: mongod --sslMode disabled
    networks:
      - my_network


  your_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: authservice
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
